-- Safe Setup Script (Idempotent)
-- This script will create tables only if they don't exist and reset policies.

-- 1. Create News Table
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  date text,
  category text,
  is_new boolean default false
);

-- 2. Create Hall of Fame Table
create table if not exists public.hall_of_fame (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  description text,
  image text
);

-- 3. Create Publications Table
create table if not exists public.publications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  url text,
  tags text[]
);

-- 4. Enable Row Level Security (RLS)
alter table public.news enable row level security;
alter table public.hall_of_fame enable row level security;
alter table public.publications enable row level security;

-- 5. Create Policies (Drop first to avoid errors)

-- Policies for News
drop policy if exists "Public Read News" on public.news;
drop policy if exists "Admin Write News" on public.news;
-- Remove old policies if any
drop policy if exists "Enable read access for all users" on public.news;
drop policy if exists "Enable insert for authenticated users only" on public.news;
drop policy if exists "Enable update for authenticated users only" on public.news;
drop policy if exists "Enable delete for authenticated users only" on public.news;

create policy "Public Read News" on public.news for select using (true);
create policy "Admin Write News" on public.news for all to authenticated using (true);

-- Policies for Hall of Fame
drop policy if exists "Public Read HallOfFame" on public.hall_of_fame;
drop policy if exists "Admin Write HallOfFame" on public.hall_of_fame;

drop policy if exists "Enable read access for all users" on public.hall_of_fame;
drop policy if exists "Enable insert for authenticated users only" on public.hall_of_fame;
drop policy if exists "Enable update for authenticated users only" on public.hall_of_fame;
drop policy if exists "Enable delete for authenticated users only" on public.hall_of_fame;

create policy "Public Read HallOfFame" on public.hall_of_fame for select using (true);
create policy "Admin Write HallOfFame" on public.hall_of_fame for all to authenticated using (true);

-- Policies for Publications
drop policy if exists "Public Read Publications" on public.publications;
drop policy if exists "Admin Write Publications" on public.publications;

drop policy if exists "Enable read access for all users" on public.publications;
drop policy if exists "Enable insert for authenticated users only" on public.publications;
drop policy if exists "Enable update for authenticated users only" on public.publications;
drop policy if exists "Enable delete for authenticated users only" on public.publications;

create policy "Public Read Publications" on public.publications for select using (true);
create policy "Admin Write Publications" on public.publications for all to authenticated using (true);
