-- Copy and paste this SQL into your Supabase SQL Editor to set up the tables

-- 1. Create News Table
create table public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  date text,
  category text,
  is_new boolean default false
);

-- 2. Create Hall of Fame Table
create table public.hall_of_fame (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  description text,
  image text
);

-- 3. Create Publications Table
create table public.publications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  url text,
  tags text[] -- Array of strings
);

-- 4. Enable Row Level Security (RLS)
alter table public.news enable row level security;
alter table public.hall_of_fame enable row level security;
alter table public.publications enable row level security;

-- 5. Create Policies (Public Read, Authenticated Write)
-- Allow everyone to read
create policy "Enable read access for all users" on public.news for select using (true);
create policy "Enable read access for all users" on public.hall_of_fame for select using (true);
create policy "Enable read access for all users" on public.publications for select using (true);

-- Allow only authenticated users (admins) to insert/update/delete
create policy "Enable insert for authenticated users only" on public.news for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.news for update to authenticated using (true);
create policy "Enable delete for authenticated users only" on public.news for delete to authenticated using (true);

create policy "Enable insert for authenticated users only" on public.hall_of_fame for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.hall_of_fame for update to authenticated using (true);
create policy "Enable delete for authenticated users only" on public.hall_of_fame for delete to authenticated using (true);

create policy "Enable insert for authenticated users only" on public.publications for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.publications for update to authenticated using (true);
create policy "Enable delete for authenticated users only" on public.publications for delete to authenticated using (true);
